// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///  final encodedPassword = encodePassword('mm2807'); // Encode the password
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVWZhpZOh1vSLFhoTTGtQr52PhB-bQGWo',
    appId: '1:472323542984:web:0f04262af460e4ab563afd',
    messagingSenderId: '472323542984',
    projectId: 'employee-shifts-506a0',
    authDomain: 'employee-shifts-506a0.firebaseapp.com',
    databaseURL: 'https://employee-shifts-506a0-default-rtdb.firebaseio.com',
    storageBucket: 'employee-shifts-506a0.appspot.com',
    measurementId: 'G-EQEJ6S566X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWJ5WsBmBUT_i1IGRU2aYNQEN0JEf9bk',
    appId: '1:472323542984:android:382743298edee4c6563afd',
    messagingSenderId: '472323542984',
    projectId: 'employee-shifts-506a0',
    databaseURL: 'https://employee-shifts-506a0-default-rtdb.firebaseio.com',
    storageBucket: 'employee-shifts-506a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwUO1Gm5JdKxYfSZiMwb_ca5hLqdIP_Ec',
    appId: '1:472323542984:ios:eac37e039161a3d9563afd',
    messagingSenderId: '472323542984',
    projectId: 'employee-shifts-506a0',
    databaseURL: 'https://employee-shifts-506a0-default-rtdb.firebaseio.com',
    storageBucket: 'employee-shifts-506a0.appspot.com',
    iosBundleId: 'com.example.shiftsSupportPort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwUO1Gm5JdKxYfSZiMwb_ca5hLqdIP_Ec',
    appId: '1:472323542984:ios:eac37e039161a3d9563afd',
    messagingSenderId: '472323542984',
    projectId: 'employee-shifts-506a0',
    databaseURL: 'https://employee-shifts-506a0-default-rtdb.firebaseio.com',
    storageBucket: 'employee-shifts-506a0.appspot.com',
    iosBundleId: 'com.example.shiftsSupportPort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVm_K_oIyH3aSlGP8Fz_iChyiCYIlqa8',
    appId: '1:472323542984:web:476005b25f243afb563afd',
    messagingSenderId: '472323542984',
    projectId: 'employee-shifts-506a0',
    authDomain: 'employee-shifts-506a0.firebaseapp.com',
    databaseURL: 'https://employee-shifts-506a0-default-rtdb.firebaseio.com',
    storageBucket: 'employee-shifts-506a0.appspot.com',
    measurementId: 'G-J3WV4RHVZH',
  );

}